apiVersion: v1
description: A Helm chart for Area server
name: area-server
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - email: ou.est@la.pierre
    name: ou-est laPierre
    url: https://Poche/Pierre