namespace: deployment

deployment:
  replicas: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  ports:
    - containerPort: 8081
  env:
    - name: DB_HOST
      value: mariadb.default.svc.cluster.local
    - name: DB_PORT
      value: "3306"
    - name: DB_USER
      value: root
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mariadb-password
          key: mariadb-root-password
    - name: DB_NAME
      value: area-api-db

volume:
  name: apk
  size: 3Gi

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081
  restartPolicy: Always

image:
  repository: registry.area.tech.showmyteam.fr/b-dev-500_area_client_web
  tag: latest
  pullPolicy: IfNotPresent